<#
.SYNOPSIS
    Syncs AGENTS.md content to .github/copilot-instructions.md

.DESCRIPTION
    This script is OPTIONAL and only needed if you decide to duplicate content
    instead of using references. Currently, .github/copilot-instructions.md
    references AGENTS.md instead of duplicating it.
    
    Use this script if you want to fully duplicate AGENTS.md content with
    an auto-sync header for GitHub Copilot compatibility.

.EXAMPLE
    .\scripts\sync-instructions.ps1
    
.EXAMPLE
    .\scripts\sync-instructions.ps1 -Verbose
#>

[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"

# Determine paths
$scriptPath = $PSScriptRoot
$rootPath = Split-Path -Parent $scriptPath
$sourcePath = Join-Path $rootPath "AGENTS.md"
$targetPath = Join-Path $rootPath ".github\copilot-instructions.md"

Write-Host ""
Write-Host "🔄 AI Instructions Sync Utility" -ForegroundColor Cyan
Write-Host "================================" -ForegroundColor Cyan
Write-Host ""

# Validate source exists
if (-not (Test-Path $sourcePath)) {
    Write-Error "❌ Source file not found: $sourcePath"
    exit 1
}

Write-Verbose "Source: $sourcePath"
Write-Verbose "Target: $targetPath"

# Read source content
try {
    $content = Get-Content $sourcePath -Raw -ErrorAction Stop
    Write-Host "✅ Read source file: AGENTS.md ($($content.Length) chars)" -ForegroundColor Green
}
catch {
    Write-Error "❌ Failed to read source file: $_"
    exit 1
}

# Create sync header
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$header = @"
<!-- 
    ⚠️ AUTO-SYNCED FROM AGENTS.md
    
    This file is automatically generated from AGENTS.md for GitHub Copilot compatibility.
    
    DO NOT EDIT THIS FILE DIRECTLY!
    - To update instructions, edit AGENTS.md in the repository root
    - Then run: scripts/sync-instructions.ps1
    
    Last synced: $timestamp
-->

"@

$syncedContent = $header + $content

# Write to target
try {
    # Ensure .github directory exists
    $githubDir = Split-Path -Parent $targetPath
    if (-not (Test-Path $githubDir)) {
        New-Item -ItemType Directory -Path $githubDir -Force | Out-Null
        Write-Verbose "Created directory: $githubDir"
    }
    
    Set-Content -Path $targetPath -Value $syncedContent -NoNewline -ErrorAction Stop
    Write-Host "✅ Synced to: .github/copilot-instructions.md" -ForegroundColor Green
}
catch {
    Write-Error "❌ Failed to write target file: $_"
    exit 1
}

# Summary
Write-Host ""
Write-Host "📊 Sync Summary" -ForegroundColor Cyan
Write-Host "   Source: AGENTS.md" -ForegroundColor Gray
Write-Host "   Target: .github/copilot-instructions.md" -ForegroundColor Gray
Write-Host "   Size:   $($syncedContent.Length) chars (including sync header)" -ForegroundColor Gray
Write-Host ""
Write-Host "📝 Note: Current project uses reference-based approach (no duplication)." -ForegroundColor Yellow
Write-Host "   This script is provided for future use if full content sync is needed." -ForegroundColor Yellow
Write-Host ""
Write-Host "✨ Done!" -ForegroundColor Green
